### 2. Переписанная статья
def dsv3_rewrite_news(client, query:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''
    min_words = int(len(query.split()) * 0.8)

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
        {"role": "system", "content": 
        f"""You are a professional journalist rewriting news content. 
        Your task is to rewrite the following article in your own words, based strictly on the facts, names, and details provided.

        Expand the article with plausible expert quotes, logical journalistic reasoning, and realistic background facts. 
        The final output must be a rich, detailed, and coherent article — but without adding any headers, disclaimers, messages about generation, or word counts.

        The response must consist **only** of the rewritten article text. 
        **Do not** include: any headlines, system messages, meta information, word counts, or technical notes of any kind.

        Make sure the article is long and substantial — **at least {min_words} words**.

        Begin rewriting the article below:
        """},
        {"role": "user", "content": f"{query}"}
        ,
        ],
        stream=False,
        max_tokens=2048,
    )
    
    return response

### 3. RF этап 1
def dsv3_evaluate_dsv3_paper(client, query:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": 
                (
                '''You are an AI assistant and an experienced news editor.
                Your task is to critically evaluate a news article and identify any signs that it may have been written or generated by a large language model (LLM), such as ChatGPT.

                Focus both on **explicit indicators** (e.g., mentions of being AI-generated, unusual disclaimers, robotic phrasing) and **stylistic or structural cues** (e.g., excessive formality, generic tone, lack of vivid detail or direct quotes).

                Provide a numbered list (1 to 10) of concrete suggestions for how the article could be revised to feel more natural, human-written, and fit for publication in a reputable news outlet.

                Do not include introductions, explanations, or summaries — only return the list of suggestions.

                Example Output:
                1) Add direct quotes from named sources or witnesses.
                2) Replace generic phrases with specific details or locations.
                3) Vary sentence length to create a more natural rhythm.
                4) Introduce subtle emotional framing to humanize the topic.
                5) Use less formal phrasing in parts of the article to match journalistic tone.
                6) Break long paragraphs into shorter, more readable segments.
                7) Include counterpoints or opposing perspectives for balance.
                8) Use stronger transitions between paragraphs.
                9) Avoid repetitive sentence structures.
                10) Add a descriptive, narrative opening rather than a summary.'''
                )},
            {"role": "user", "content": f"Article text: {query}"},
        ],
        stream=False,
        max_tokens=512
    )
    
    return response


def dsv3_rewrite_dsv3_paper(client, news_article:str, suggestions:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {
            "role": "system",
            "content": (
                '''You are a skilled news editor working for a major publication.
            You are given a draft news article and a list of editorial suggestions from a senior editor.

            Your task is to rewrite the article, improving it by fully incorporating all the suggestions provided.
            Your primary goal is to eliminate any signs that the article might have been written by an AI, and make it feel fully human-written and suitable for a professional news outlet.

            Instructions:
            - Do not omit any important information from the original article.
            - Maintain the original topic and factual content.
            - Improve tone, specificity, rhythm, flow, and narrative depth.
            - You may rearrange sentences, rewrite paragraphs, and add illustrative examples, background, or quotes, as long as the core meaning remains the same.
            - Use natural journalistic style, avoid templated or overly formal language.
            - You are encouraged to insert vivid quotes, specific names, emotional nuance, and narrative color to bring the piece to life.

            Return only the rewritten article. Do not include a title, explanation, or any other text.'''
            )
            },
            {
            "role": "user",
            "content": f"""Editorial suggestions:
            {suggestions}

            Original news article:
            {news_article}"""
            }
        ],
        stream=False,
        max_tokens=2048
    )
    
    return response

### 4. RF этап 2
def dsv3_evaluate_dsv3_paper_v2(client, original_query:str, generated_article:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": 
                (
                '''You are an experienced journalist and media analyst. Your task is to compare a real news article with a machine-generated rewrite of the same story.
                Please identify the **top 5 stylistic and narrative differences** between the original article and the generated version. 
                Focus on tone, sentence rhythm, emotional framing, lexical variety, and realism of quotes or detail. 
                Return only a **bullet-point list of five clear differences** — do not summarize the articles or make recommendations.'''
                )},
            {"role": "user", 
            "content": f"Original article: \n{original_query}. \nGenerated article: \n{generated_article}"},
        ],
        stream=False,
        max_tokens=512
    )
    
    return response


def dsv3_rewrite_dsv3_paper_v2(client, news_article:str, suggestions:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    min_words = int(len(news_article.split()) * 0.95)

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
                {
                "role": "system",
                "content": (
                    f'''You are an experienced journalist and news editor. 
                    Your task is to rewrite a generated article so that it matches the stylistic quality and tone of a professional, human-written news article. 
                    You are given stylistic feedback that highlights key differences between the original article and the generated version. 
                    You must use these insights to revise the generated article.
                    Make sure the article is long and substantial — **at least {min_words} words**.
                    \n\nInstructions:
                    - Do not copy full sentences or paragraphs from the original article.
                    - You may freely rewrite, restructure, shorten, or expand the text.
                    - Evaluate the plausibility and naturalness of quotes and descriptions — do not check for factual accuracy or source alignment.
                    - Avoid artificial storytelling (no fictional characters or overly dramatized scenes). 
                    - **Do not** include: any headlines, system messages, meta information, word counts, or technical notes of any kind.
                    Your output should contain only the final news article text — no titles, no lists, and no commentary.

'''
                )
                },
                {
                "role": "user",
                "content": f"""Differences to fix:\n{suggestions}

                Generated article to rewrite:\n{news_article}"""
                }

        ],
        stream=False,
        max_tokens=2048
    )
    
    return response

### 5. RF этап 3
def dsv3_evaluate_dsv3_paper_v3(client, generated_article:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": 
                (
                '''You are a senior news editor specializing in identifying and correcting language model (LLM)-generated articles. 
                Your job is to carefully analyze the article and identify stylistic or structural issues that are common in LLM-generated text but uncommon in professionally written journalism.'''
                '''Please read the user content and return a list of the top 2 or 5 specific issues that make it resemble an LLM-generated text. 
                Each point should:\n- Clearly identify a pattern (e.g. quote style, rhythm, word choice, structure)\n- Describe how it differs from typical human-written journalism\n- Be phrased as an editorial suggestion to improve the text.'''
                )},
            {"role": "user", 
            "content": f"User content:\n{generated_article}"},
        ],
        stream=False,
        max_tokens=512
    )
    
    return response


def dsv3_rewrite_dsv3_paper_v3(client, news_article:str, suggestions:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    min_words = int(len(news_article.split()))

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
        {
        "role": "system",
        "content": (
            "You are a professional journalist and editor. You are given a draft article and a list of specific editorial suggestions that address common signs of LLM-generated writing. "
            "Your task is to rewrite the article to apply all suggestions and make the piece feel more authentic, human-written, and journalistic. "
            "Keep the topic, facts, and structure, but you may rewrite wording, sentence rhythm, tone, and quote realism. "
            "Do not include any headlines, subheadings, author bylines, editorial credits, or additional metadata. "
            f"Make sure the article is long and substantial — **at least {min_words} words**."
            "**Do not** include: any headlines, system messages, meta information, word counts, or technical notes of any kind."
            "Your output should be only the rewritten body of the article, as it would appear in print — no titles, no section labels, no attributions like 'reporting by'."
        )
        },
        {
        "role": "user",
        "content": "Suggestions to fix:\n" + suggestions + "\n\nGenerated article to rewrite:\n" + news_article
        }

        ],
        stream=False,
        max_tokens=2048
    )
    
    return response

### 6. Редактивроание статьи - уход от аналитической записки
def dsv3_rewrite_dsv3_paper_v5(client, news_article:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    min_words = int(len(news_article.split()))

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
    {  
        "role": "system",  
        "content":   
            "You are a seasoned journalist tasked with adding 'human texture' to an AI-generated article. Apply these edits:\n\n"  
            "1. **Inject Noise & Incongruence**:\n"  
            "   - Add 1-2 meaningless background actions per scene (e.g., 'She taps her pen rhythmically against a stale donut')\n"  
            "   - Insert 1 abrupt tonal shift per 3 paragraphs (e.g., factual → sarcastic aside)\n\n"  
            "2. **Disrupt Rhythm**:\n"  
            "   - Replace 10% of polished transitions with fragmented phrases or dashes\n"  
            "   - Make at least one quote trail off mid-sentence\n\n"  
            "3. **Degrade Dialogue**:\n"  
            "   - Add filler words ('um,' 'like'), interruptions, or unfinished thoughts to 70% of quotes\n"  
            "   - Make one speaker contradict themselves mildly\n\n"  
            "4. **Insert Irrelevant Details**:\n"  
            "   - Mention a trivial object in every scene (e.g., 'a cracked iPhone case')\n"  
            "   - Add one pointless anecdote (e.g., 'He mentions his cat’s birthday—April 1st, ironically')\n\n"  
            "5. **Post-Edit for Style**:\n"  
            "   - Rewrite 20% of sentences using a contrasting voice (e.g., academic → tabloid)\n"  
            "   - Add one grammatically incorrect but colloquial phrase (e.g., 'Ain’t nobody got time for that')\n\n"  
            f"Make sure the article is long and substantial — **at least {min_words} words**."
            "**Do not** include: any headlines, system messages, meta information, word counts, or technical notes of any kind."
            "Prioritize natural imperfection over coherence. Retain core facts but make the text feel like a first draft with personality."  
            "RETURN ONLY ARTICLE TEXT WITHOUT TITILE"
    },  
    {  
        "role": "user",  
        "content": f"Humanize this article:\n\n{news_article}"  
    }  
        ],
        stream=False,
        max_tokens=2048
    )
    
    return response

### 7. Редактивроание статьи - подгонка под новостную статью
def dsv3_rewrite_dsv3_paper_v6(client, news_article:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    min_words = int(len(news_article.split()))

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
{
    "role": "system",
    "content":   
        f'''You are a political news editor tasked with rewriting informal local reports into the structured, formal style of a BBC Politics column.
        Rewrite the following article into a formal, analytical column, ensuring the following:
        * Use a formal and analytical tone without slang, irony, or overly emotional language.
        * Begin with a clear, informative headline and a concise summary lead.
        * Maintain journalistic objectivity and distance, avoiding personal opinions.
        * Paraphrase informal expressions into neutral, factual language while preserving the article’s key points.
        * Where appropriate, add context, background information, and implications of the events.
        * Do not use placeholders like [Your Name], Political Correspondent.
        * Ensure the article is comprehensive and well-structured, with a length of at least {min_words} words.
        * Avoid including any headlines, system messages, meta information, or technical notes.
        Here's the article:'''
},
{
    "role": "user",
    "content": f"Humanize this article:\n\n{news_article}"
}
        ],
        stream=False,
        max_tokens=2048
    )
    
    return response



def create_responce_dsv3(client, query:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''
    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": f"You're the editor of a news article! Your task is to process an article from an intern who used LLM! You need to remove everything from the article that does not relate to its topic, such as model artifacts, model warnings about generated texts, and word counts. Your task is to leave only the text of the article unchanged, deleting only what does not relate to the article itself. Process this text and respond ONLY with the news article itself:"},
            {"role": "user", "content": f"{query}"},
        ],
        stream=False,
        max_tokens=1024,  # Максимальное (если нужно ограничить)
    )
    
    return response

def dsv3_create_news(client, query:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": 
                (
                    "You - AI-asistant - Author of news! "
                    "Your task is to write an article! Come up with a situation on the topic of the proposed topic! "
                    "If they give you a biography of a person, use that person's name in the article! "
                    "Try to describe what is happening in detail, as if you were the author of the London Guardian newspaper! "
                    "**The story should be logical and consistent! Write long paper 300-800 words!**"
                    "**Do not write any information other than the article itself, do not write title!**"
                    "**The content contains a title and possibly a biography**!"
                )},
            {"role": "user", "content": f"{query}"},
        ],
        stream=False,
        max_tokens=2048
    )
    
    return response


def dsv3_api_request(client, query:str, system_content:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": f"{system_content}"},
            {"role": "user", "content": f"{query}"},
        ],
        stream=False,
        max_tokens=4096
    )
    
    return response


def dsv3_create_long_news(client, query:str):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": 
                (
                "You are an AI assistant and a skilled news journalist."
                "Your task is to analyze the short article below and expand it into a longer, more detailed and immersive article, while maintaining the original topic and logical structure."
                "* Use vivid and descriptive language, like a Guardian newspaper reporter."
                "* The final article should be between 600 and 1200 words."
                "* Add details, background, quotes, or context where needed."
                "* Keep the tone consistent with professional journalism."
                "Only output the expanded article — no explanations, no titles, no formatting instructions."
                "The original article to expand in content!"
                )},
            {"role": "user", "content": f"{query}"},
        ],
        stream=False,
        max_tokens=4096
    )
    
    return response


def dsv3_clean_orig_news(client, titile:str, paper):
    '''Функция для создания промпта к модели DeepSeek-v3'''

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": 
                (
                    '''
                    You are acting as a chief news editor approving articles for publication.

                    Input: 
                    You receive an article title and full article text.

                    Your task:
                    Remove any content not directly part of the article’s main body.

                    Specifically, delete:
                    "Promotions for other articles ("Read more", "Listen to this", "What’s on the grid", "Quote of the day", etc.)"
                    "Technical notes (e.g., "Last updated", "First published on...", timestamps)"
                    "Advertisements, subscription prompts, or unrelated sections."
                    "Block 'Related: '"
                    "Do not change, rewrite, or paraphrase any sentences from the main article."

                    Clean the text by:
                    "Removing any random or corrupted characters (e.g., Â, �, stray quotation marks, duplicate punctuation, artifacts from encoding issues)."
                    "Removing sentences that are obviously unrelated or incorrectly merged due to formatting errors (for example, two sentences mashed together without logic because of a line break)."
                    "Do not rewrite, change, or paraphrase any valid sentences from the main article."
                    "If a sentence fragment is detected that lacks logical context or is an incomplete thought (e.g., "he is washing an ambulance"), remove the incomplete fragment."

                    Output Requirements:
                    "Return only the cleaned article text."
                    "Do not include the title."
                    "Do not add any comments, notes, explanations, or formatting."
                    "No markdown formatting, no extra text — only the cleaned article body."'''
                )},
            {"role": "user", "content": f"Article title: {titile}, Article text: {paper}"},
        ],
        stream=False,
        max_tokens=4096
    )
    
    return response







